EventsProject/Controllers/TicketController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventsProject.Controllers
{
    public class TicketController : Controller
    {
        
        TicketManager tm = new TicketManager(new EfTicketDal());
        EventManager em = new EventManager(new EfEventDal());
        Context c = new Context();



        public ActionResult Index()
        {
            tm.TicketDate(); // Süresi Geçen Bileti Kontrol Eden Metot
            return View();
        }

        [HttpGet]
        public ActionResult BuyTicket(int id)
        {
            var ticket = c.Events.FirstOrDefault(x=>x.EventId==id);
            return View(ticket);
        }

        [HttpPost]
        public ActionResult BuyTicket(Ticket p)
        {
            string username = (string)Session["UserName"];
            int userIdInfo = c.Users.Where(x => x.UserName == username).Select(y => y.UserID).FirstOrDefault();


            tm.TicketAdd(p, userIdInfo);
            return RedirectToAction("YourTicket");

        }

        public ActionResult YourTicket(Ticket p) 
        {
            int id = p.TicketId;

            var ticketValue = tm.GetByID(id);
            return View(ticketValue);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult CheckTicket()
        {   
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult CheckTicket(Ticket t)
        {

            if (tm.CheckTicket(t))
            {
                ViewBag.CheckTicket = "Biletiniz Geçerlidir.";
            }
            else
            {
                ViewBag.CheckTicket = "Geçersiz Bilet";
            }

            return View();
        }

    }
}

EventsProject/Controllers/UserPanelController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventsProject.Controllers
{
    public class UserPanelController : Controller
    {
        // GET: UserPanel
        EventManager em = new EventManager(new EfEventDal());
        AllowEventManager aem = new AllowEventManager(new EfAllowEventDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        UserManager um = new UserManager(new EfUserDal());
        CityManager ctm = new CityManager(new EfCityDal());
        TicketManager tm = new TicketManager(new EfTicketDal());

        UserValidator userValidator = new UserValidator();

        Context c = new Context();


        public ActionResult Index()
        {
            var eventValues = em.GetList();
            return View(eventValues);
        }
        [HttpGet]
        public ActionResult UserProfile(int id=1)
        {
            string p = (string)Session["UserName"];
            id = c.Users.Where(x => x.UserName == p).Select(y => y.UserID).FirstOrDefault();
            var userValue = um.GetByID(id);
            return View(userValue);
        }
        [HttpPost]
        public ActionResult UserProfile(User p)
        {
            ValidationResult results = userValidator.Validate(p);
            if (results.IsValid)
            {
                um.UserUpdate(p);
                return RedirectToAction("UserProfile");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult MyTicket(string p)
        {
            p = (string)Session["UserName"];
            var userIdInfo = c.Users.Where(x => x.UserName == p).Select(y => y.UserID).FirstOrDefault();

            var values = tm.GetListByUser(userIdInfo);

            return View(values);
        }

        public ActionResult MyEvent(string p)
        {

            p = (string)Session["UserName"];
            var userIdInfo = c.Users.Where(x=> x.UserName == p).Select(y=>y.UserID).FirstOrDefault();
            var values = em.GetListByUser(userIdInfo);
            return View(values);
        }
        public PartialViewResult UserProfilePartial()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult NewEvent()
        {   
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString(),
                                                  }).ToList();
            List<SelectListItem> valueCity = (from x in ctm.GetList()
                                              select new SelectListItem
                                              {
                                                  Text = x.CityName,
                                                  Value = x.CityName,
                                              }).ToList();
            ViewBag.city = valueCity;
            ViewBag.vlc = valueCategory;
            return View();
        }
        [HttpPost]  
        public ActionResult NewEvent(AllowEvent p)
        {
            string username = (string)Session["UserName"];
            var userIdInfo = c.Users.Where(x => x.UserName == username).Select(y => y.UserID).FirstOrDefault();
           

            p.UserID = userIdInfo;
            p.AllowEventStatus = true;
            p.CheckStatus = false;
            aem.AllowEventAdd(p);

            return RedirectToAction("MyEvent");
        }

        [HttpGet]
        public ActionResult EditEvent(int id)
        {

            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString(),
                                                  }).ToList();

            var cities = ctm.GetList();

            var valueCity = cities.Select(c => new SelectListItem
                                                    {
                                                        Value = c.CityName,
                                                        Text = c.CityName
                                                    }).ToList();

            ViewBag.city = valueCity;
            ViewBag.vlc = valueCategory;

            var eventValue = em.GetByID(id);
            return View(eventValue);

        }
        [HttpPost]
        public ActionResult EditEvent(Event p)
        {
            string username = (string)Session["UserName"];
            var userIdInfo = c.Users.Where(x => x.UserName == username).Select(y => y.UserID).FirstOrDefault();


            p.UserID = userIdInfo;
            p.EventStatus= true;
            em.EventUpdate(p);
            //if (em.EventUpdate2(p))
            //{
            //    return RedirectToAction("MyEvent");
            //}
            //else 
            //{
            //    ViewBag.UpdateError = "Etkinliğe son 5 gün kaldığı için değişiklik yapamazsınız.";
            //}
            return View();
        }


    }
}

EventsProject/Views/UserPanel/EditEvent.cshtml
@model EntityLayer.Concrete.Event

@{
    ViewBag.Title = "EditEvent";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<section class="service-single">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                @Html.Action("UserProfilePartial", "UserPanel")
            </div>
            <div class="col-md-9">
                <div class="outer-box">
                    <section class="content-header">
                        <div class="container-fluid">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h1>Etkinlik Düzenle</h1>
                                </div>
                            </div>
                        </div>
                    </section>
                    <section class="content">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Düzenle</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body p-0">
                                <br />
                                <p class="w-100 text-center">@ViewBag.UpdateError</p>
                                @using (Html.BeginForm("EditEvent", "UserPanel", FormMethod.Post))
                                {

                                    <div class="form-group">
                                        @Html.HiddenFor(x => x.EventId)
                                        @Html.Label("Etkinlik Adı")
                                        @Html.TextBoxFor(x => x.EventName, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(x => x.EventName)

                                        <br />
                                        @Html.Label("Lokasyon")
                                        @Html.DropDownListFor(x => x.EventLoc, (IEnumerable<SelectListItem>)ViewBag.city, new { @class = "form-control" })

                                        <br />

                                        @Html.Label("Açıklama")
                                        @Html.TextBoxFor(x => x.EventDescription, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(x => x.EventDescription)
                                        <br />
                                        @Html.Label("Etkinlik Zamanı")
                                        @Html.TextBoxFor(x => x.EventDate, new { @class = "datetimepicker", placeholder = "Tarih ve Saati Seçiniz" })

                                        <br />
                                        @Html.Label("Kontenjan")
                                        @Html.TextBoxFor(x => x.EventQuota, new { @class = "form-control" })

                                        <br />
                                        @Html.Label("Etkinlik Kategorisi")
                                        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })

                                        <br />
                                        <button class="btn btn-info">Düzenle</button>
                                        <a class="btn btn-success" href="@Url.Action("MyEvent","UserPanel")">Geri Dön</a>
                                    </div>
                                }

                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>

EventsProject/Views/UserPanel/Index.cshtml
@using EntityLayer.Concrete
@model List<Event>


@{
    ViewBag.Title = "UserProfile";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


@{ string color = "";}
@{ string status = "";}

<section class="services-two bg-1 padd-3">
    <div class="container">

        <section class="services-two bg-1 padd-3">
            <div class="container">
                <br />
                <h1 class="text-center">Yaklaşan Etkinlikler</h1>
                <br />
                <section class="content">
                    <div class="card">
                        <div class="card-body p-0">
                            <table class="table table-striped projects">
                                <thead>
                                    <tr>
                                        <th style="width: 1%" class="text-center">
                                            #
                                        </th>
                                        <th style="width: 20%" class="text-center">
                                            Etkinlik Adı
                                        </th>
                                        <th style="width: 20%" class="text-center">
                                            Lokasyonu
                                        </th>
                                        <th style="width: 15%" class="text-center">
                                            Açıklama
                                        </th>
                                        <th style="width: 10%" class="text-center">
                                            Kontenjanı
                                        </th>
                                        <th style="width: 25%" class="text-center">
                                            Kategori
                                        </th>
                                        <th style="width: 15%" class="text-center">
                                            Oluşturan Kullanıcı
                                        </th>

                                        <th style="width: 30%">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {

                                        if (item.Category.CategoryName == "Tiyatro")
                                        {
                                            color = "badge badge-warning";

                                        }
                                        if (item.Category.CategoryName == "Spor")
                                        {
                                            color = "badge badge-success";

                                        }
                                        if (item.Category.CategoryName == "Yazılım")
                                        {
                                            color = "badge badge-info";

                                        }


                                        <tr>
                                            <td>
                                                @item.EventId
                                            </td>
                                            <td class="text-center">
                                                <a class="text-center">
                                                    @item.EventName
                                                </a>
                                                <br />
                                                <small>
                                                    @(((DateTime)item.EventDate).ToString("dd/MMM/yyyy - hh:mm"))
                                                </small>
                                            </td>
                                            <td class="text-center">
                                                @item.EventLoc
                                            </td>

                                            <td class="text-center">
                                                @item.EventDescription
                                            </td>
                                            <td class="text-center">
                                                @item.EventQuota
                                            </td>
                                            <td class="project-state text-center">
                                                <span class="@color">@item.Category.CategoryName</span>
                                            </td>
                                            <td>
                                                <ul class="list-inline text-center">
                                                    <li class="list-inline-item">
                                                        <a>
                                                            @item.User.UserName
                                                        </a>
                                                    </li>
                                                </ul>
                                            </td>
                                            <td>
                                                @Html.ActionLink("Bilet Al", "BuyTicket", "Ticket", new { id = @item.EventId }, new { @class = "btn btn-info" })
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </section>

            </div>
        </section>

    </div>
</section>

EventsProject/Views/UserPanel/MyEvent.cshtml
@using EntityLayer.Concrete
@model List<Event>

@{
    ViewBag.Title = "MyEvent";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}



@{ string color = "";}

<section class="service-single">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                @Html.Action("UserProfilePartial", "UserPanel")
            </div>
            <div class="col-md-9">
                <div class="outer-box">
                    <section class="content-header">
                        <div class="container-fluid">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h1>Etkinliklerim</h1>
                                </div>
                            </div>
                        </div>
                    </section>
                    <section class="content text-center">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Etkinlik İşlemleri</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body p-0">
                                <table class="table table-striped projects">
                                    <thead>
                                        <tr class="text-center">
                                            <th style="width: 1%">
                                                #
                                            </th>
                                            <th style="width: 20%" class="text-center">
                                                Etkinlik Adı
                                            </th>
                                            <th style="width: 20%" class="text-center">
                                                Açıklama
                                            </th>
                                            <th style="width: 15%" class="text-center">
                                                Kontenjan
                                            </th>
                                            <th style="width: 8%" class="text-center">
                                                Kategori
                                            </th>
                                            <th style="width: 30%" class="text-center">
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {

                                            if (item.Category.CategoryName == "Tiyatro")
                                            {
                                                color = "badge badge-warning";

                                            }
                                            if (item.Category.CategoryName == "Spor")
                                            {
                                                color = "badge badge-success";

                                            }
                                            if (item.Category.CategoryName == "Yazılım")
                                            {
                                                color = "badge badge-info";

                                            }

                                            <tr>
                                                <td>
                                                    @item.EventId
                                                </td>
                                                <td>
                                                    <a>
                                                        @item.EventName
                                                    </a>
                                                    <br />
                                                    <small>
                                                        @(((DateTime)item.EventDate).ToString("dd/MMM/yyyy - hh:mm"))
                                                    </small>
                                                </td>
                                                <td>
                                                    @item.EventDescription
                                                </td>
                                                <td>
                                                    @item.EventQuota
                                                </td>

                                                <td class="project-state">
                                                    <span class="@color">@item.Category.CategoryName</span>
                                                </td>
                                                <td class="project-actions text-right">
                                                    <a class="btn btn-primary btn-sm" href="#">
                                                        <i class="fas fa-folder">
                                                        </i>
                                                        İncele
                                                    </a>
                                                    <a class="btn btn-info btn-sm" href="/UserPanel/EditEvent/@item.EventId">
                                                        <i class="fas fa-pencil-alt">
                                                        </i>
                                                        Düzenle
                                                    </a>
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </section>

                    <a class="btn btn-primary" href="/UserPanel/NewEvent/">Etkinlik Oluştur</a>

                </div>
            </div>
        </div>
    </div>
</section>

EventsProject/Views/UserPanel/MyTicket.cshtml
@using EntityLayer.Concrete
@model List<Ticket>

@{
    ViewBag.Title = "MyEvent";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}



<section class="service-single">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                @Html.Action("UserProfilePartial", "UserPanel")
            </div>
            <div class="col-md-9">
                <div class="outer-box">
                    <section class="content-header">
                        <div class="container-fluid">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h1>Biletlerim</h1>
                                </div>
                            </div>
                        </div>
                    </section>
                    <section class="content">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Bilet İşlemleri</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body p-0">
                                <table class="table table-striped projects">
                                    <thead>
                                        <tr>
                                            <th style="width: 1%">
                                                #
                                            </th> 
                                            <th style="width: 20%" class="text-center">
                                                Etkinlik Adı
                                            </th>
                                            <th style="width: 20%" class="text-center">
                                                Açıklama
                                            </th>
                                            <th style="width: 20%" class="text-center">
                                                Bilet Numarası
                                            </th>
                                            <th style="width: 8%" class="text-center">
                                                Kategori
                                            </th>
                                            <th style="width: 20%">
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {


                                            <tr>
                                                <td class="text-center">
                                                    @item.e.EventId
                                                </td>
                                                <td class="text-center">
                                                    <a>
                                                        @item.e.EventName
                                                    </a>
                                                    <br />
                                                    <small>
                                                        @(((DateTime)item.e.EventDate).ToString("dd/MMM/yyyy - hh:mm"))
                                                    </small>
                                                </td>
                                                <td class="text-center">
                                                    @item.e.EventDescription
                                                </td>

                                                <td class="text-center">
                                                    @item.TicketNumber
                                                </td>

                                                <td class="project-state text-center">
                                                    <span class="badge badge-warning">@item.e.Category.CategoryName</span>
                                                </td>

                                             

                                                <td class="project-actions text-right">
                                                    
                                                    <a class="btn btn-info btn-sm" href="#">
                                                        <i class="fas fa-pencil-alt">
                                                        </i>
                                                        PDF Olarak İndir
                                                    </a>
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </section>

                </div>
            </div>
        </div>
    </div>
</section>

EventsProject/Views/UserPanel/UserProfilePartial.cshtml
<div class="service-sidebar">
    <ul class="service-catergory">
        <li class=""><a href="/UserPanel/UserProfile/">Profil Bilgilerim</a> <span class="view-all-icon fa fa-caret-right"></span></li>
        <li class=""><a href="/UserPanel/MyTicket/">Biletlerim</a><span class="view-all-icon fa fa-caret-right"></span></li>
        <li class=""><a href="/UserPanel/MyEvent/">Etkinliklerim</a><span class="view-all-icon fa fa-caret-right"></span></li>
    </ul>
    <br>
    <br>
</div>